# Generated by Django 5.2.8 on 2025-11-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
